### ISSUE TITLE
Distance fog

### ISSUE THREAD

**Issue by Uriopass** [Uriopass/Egregoria#102]
Kinda ready but I fear it would destroy lower end gpus

https://github.com/Uriopass/Egregoria/assets/5420739/3f41d180-98ed-4d09-91d2-0dc603fa2113

I need to implement this paper: https://sebh.github.io/publications/egsr2020.pdf

**Comment by lou19822** [comment]
utdrcjyc

**Comment by lou19822** [comment]
1. #fOfOfO
