### ISSUE TITLE
Chaining streets shouldn't create intersections

### ISSUE THREAD

**Issue by AntonioNoack** [Uriopass/Egregoria#111]
I was creating a longer than usual road, image a country-side road, and it's weird to have intersections for a continous road.

![image](https://github.com/Uriopass/Egregoria/assets/20659579/e676043d-38bd-49b6-89e2-31b7fb4e5c15)

As a plus, I'm positively surprised that your project works out of the box 😃

**Comment by Uriopass** [comment]
Absolutely, this has been on my mind for a while and I've done the prepping work for this, I just need to get going.

**Comment by Uriopass** [comment]
Oh yeah now what happens when a road connects to itself... 
![image](https://github.com/user-attachments/assets/29d2172a-8818-4218-9f45-909110e80833)

Currently doing some weird things.. I'm starting to understand more and more why cities skylines works the way it does with its "road segments".

**Comment by Uriopass** [comment]
Decided to merge only if the roads are aligned enough (<25° angle) and if they dont lead to themselves
