### ISSUE TITLE
Tooltip text for left-most items goes off-screen

### ISSUE THREAD

**Issue by AntonioNoack** [Uriopass/Egregoria#112]
Hey, in the building menu, the tooltip text is off the screen, when there's enough items to fill the whole screen width:

![image](https://github.com/Uriopass/Egregoria/assets/20659579/64300fb4-60e3-416c-b152-419ac9aeaedb)

The bakery should have shown its text completely.

**Comment by Uriopass** [comment]
Nice catch, I'll try to make a yakui generic component (in goryak) for this.
