### ISSUE TITLE
Terrain Erosion is much faster than Elevation/Smooth/Level

### ISSUE THREAD

**Issue by AntonioNoack** [Uriopass/Egregoria#115]
I was surprised how quickly the terrain was eroded when I tried it. Imo all tools should have roughly the same speed changing terrain.

![image](https://github.com/Uriopass/Egregoria/assets/20659579/3db7ab22-1b42-4102-981b-b358fb4ef801)
(just an image of what I tried 😄, not really useful for the topic at hand)

**Comment by AntonioNoack** [comment]
Another small spelling thing:
![image](https://github.com/Uriopass/Egregoria/assets/20659579/9c3066be-1d52-4782-840e-ac2e4f8925ea)

**Comment by Uriopass** [comment]
Erosion doesn't use the same system as the rest so it's harder to control for this but you're absolutely right, should be easy to tune to tone it down depending on speed.
