### ISSUE TITLE
Wondering how to contribute?

### ISSUE THREAD

**Issue by skairunner** [Uriopass/Egregoria#16]
Hi, I was toying with the idea of making a traffic simulator in Rust, and I was trawling the web trying to figure out which graphics library or game engine to use (Amethyst, ggez, gfx, wgpu, vulkano, glium, gd, the list goes on and on), or whether I should be using 2D or 3D, and I found Egregoria, which seems to have things in common with what I wanted to make. 

I'm wondering how best to talk to you or other people working on this about what's going on?

**Comment by skairunner** [comment]
Also, the first thing I did was spawn ten thousand vehicles to cause deadlock, which might amuse you.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/3517115/89414648-0ffc9b00-d72b-11ea-997a-6213c9c8c85f.png">

**Comment by Uriopass** [comment]
You can add me on discord
Uriopass#1988

or join the discord server which I haven't advertised yet and is very small
https://discord.gg/CAaZhUJ

**Comment by skairunner** [comment]
Cool.
