### ISSUE TITLE
Trains and subway systems

### ISSUE THREAD

**Issue by Uriopass** [Uriopass/Egregoria#38]
Freight/passenger trains are undoubtedly cool looking and fun to play with. Although it might take a bit of time to implement, my experience with the road system should make it easier to build, at least for the tracks.

Also, subway make a city faster and could solve some traffic issues.

**Comment by Uriopass** [comment]
Train system is pretty much done. (Rails, train routing, train collision avoidance.)
Now it's more about the less fun plumbing of things together to make it work.

Subways are not implemented yet, maybe later.

**Comment by shoegazin** [comment]
allowing housing to be built near train tracks or in the future subway stations, to allow for car free play throughs
