### ISSUE TITLE
UI scale is too small

### ISSUE THREAD

**Issue by johann2** [Uriopass/Egregoria#64]
On a 4k monitor it's almost unreadable. On a FHD monitor it's still uncomfortably small.

Ideally a setting for UI scale would be nice, but a larger hardcoded/default value would already help a lot.

**Comment by Uriopass** [comment]
Blocked on https://github.com/emilk/egui/issues/2038 for now (increasing pixel_per_point triggers this), will fix when new egui is released as I don't really like git dependencies.

**Comment by Uriopass** [comment]
Done in https://github.com/Uriopass/Egregoria/commit/aecd5582a7b82c68158382528ee2310ddac107df

https://user-images.githubusercontent.com/5420739/200167064-9b274196-a366-4f6e-8e4e-5805afa765d4.mp4
