### ISSUE TITLE
A weird traffic deadlock

### ISSUE THREAD

**Issue by johann2** [Uriopass/Egregoria#65]
![image](https://user-images.githubusercontent.com/6451852/191526366-94591e7e-07ec-48fe-83db-7ac43a9253ac.png)
They have been like that for a couple of days now and flashing the path not found text.

**Comment by Uriopass** [comment]
If you have a simple loop like this so they cannot go the other way because back-turns are not allowed by default

![image](https://user-images.githubusercontent.com/5420739/191529216-b5acaaa6-e66d-4553-ace5-d47ef7edc8fe.png)

**Comment by Uriopass** [comment]
Many ways to solve this but anything other than a simple loop makes the whole thing work so I don't want to spend too much time on this
