### ISSUE TITLE
Left hand camera movement is weird for people not using AZERTY keyboards

### ISSUE THREAD

**Issue by johann2** [Uriopass/Egregoria#66]
Either using scancodes instead of virtual key codes or adding input remapping support would fix this.
Either way, I think that it's important that this works out of the box for everyone. 
Having to change basic controls at the start would not be a good first impression.

**Comment by Uriopass** [comment]
Yep this is planned 👍

**Comment by Uriopass** [comment]
Fixed in https://github.com/Uriopass/Egregoria/commit/bacb0a1a705e82a479051c73fa667c2f05fbe802
