### ISSUE TITLE
It's possible to build streets overlapping each other

### ISSUE THREAD

**Issue by johann2** [Uriopass/Egregoria#67]

**Comment by johann2** [comment]
I think even a simple line check with road segments on the same plane would go a long way.

**Comment by Uriopass** [comment]
Fixed in https://github.com/Uriopass/Egregoria/commit/9a3747ec07b8ebb9e0e945aec708479aa1cc2020


https://user-images.githubusercontent.com/5420739/192102603-66cfc9ad-82d8-455f-9e17-df956e5d4451.mp4
