### ISSUE TITLE
Cars don't despawn when the road is deleted under them

### ISSUE THREAD

**Issue by johann2** [Uriopass/Egregoria#68]
I had a deadlocked intersection and tried to delete it to fix this, but it didn't help and now I'm stuck with a traffic jam that only gets bigger.
Maybe add a timeout so cars that are stuck for a day would despawn/reset to their starting location and optionally add some penalty so it wouldn't become a way to teleport goods

**Comment by Uriopass** [comment]
Yeah it's a problem because cars are supposed to be persistent, someone owns them and everything. What's weird is that the traffic jam shouldn't have gridlocked you, only make everything go slowly.

**Comment by Uriopass** [comment]
I changed the traffic rules so jams are less of a problem
