### ISSUE TITLE
Most models having black rendering artifacts

### ISSUE THREAD

**Issue by Salzian** [Uriopass/Egregoria#70]
When moving the camera, there is a strong, flickering visual bug on models.

<img width="1728" alt="Screenshot 2022-11-20 at 19 21 41" src="https://user-images.githubusercontent.com/23481219/202919218-2b3e88e1-b2d6-4dfb-8c12-b45cb154e1db.png">

https://user-images.githubusercontent.com/23481219/202919539-31dd8b6f-a7ef-4c73-ba3c-cf5830421410.mov

Only these things are unaffected:

- ground plane
- roads
- rails
- residential buildings

Happening on MacBook Pro 2021

**Comment by Uriopass** [comment]
Can you send a screenshot of your graphical settings ? (In the graphics menu)

**Comment by Uriopass** [comment]
What the affected things have in common is that they are all instances rendered. Could be driver/wgpu issues around instancing on your platform or some UB on my instancing code.
