### ISSUE TITLE
Broken TV)

### ISSUE THREAD

**Issue by el1sha256** [Uriopass/Egregoria#76]
Just look to screenshot
![Screenshot from 2023-06-17 16-53-13](https://github.com/Uriopass/Egregoria/assets/45532828/b484563f-4875-47fb-a12c-a33496062798)

Log: 
[log.txt](https://github.com/Uriopass/Egregoria/files/11779179/log.txt)

System: Linux Ubuntu 20.04

**Comment by Uriopass** [comment]
This is... Surprising to say the least. I see you are using an AMD card.
Any chance you could try a git bisect to maybe find a working version and an offending commit ?

**Comment by el1sha-git** [comment]
> 

I found out that this is only on Wayland, i switched DE to Xorg and all fine, dont know why but on wayland i have a trouble

**Comment by Uriopass** [comment]
Ok interesting, I'll see if I can reproduce on wayland

**Comment by Uriopass** [comment]
Couldn't reproduce on wayland :/ I have to say wayland support in winit is not that great
