### ISSUE TITLE
Some NPCs freeze in mid air and are unable to find a path

### ISSUE THREAD

**Issue by ajh123** [Uriopass/Egregoria#77]
![image](https://github.com/Uriopass/Egregoria/assets/41990982/e8697bd1-ad47-444e-b821-d421414e2c54)

Not sure what causes this issue but what I did was open the game from my previous save. Possible the NPCs were "jumping" when they were saved but when the game loaded they did not fall down again so they are unable to find a path. 

Below is the contents of my `world_replay.json` file.
[world_replay.txt](https://github.com/Uriopass/Egregoria/files/11791165/world_replay.txt)

Also my `world.zip`
[world.zip](https://github.com/Uriopass/Egregoria/files/11791167/world.zip) (GitHub won't allow it as a `.json` so it's a `.txt` instead)

They might help to find the problem.

**Comment by Uriopass** [comment]
Which version did you use ? Latest master ? I'll take a look when I can, thank you 👍

**Comment by ajh123** [comment]
Its commit `cdbbc7f0e047e4ebd560cea17dade3a5880226a5` as it appears in `git log`. Its the latest "master".

**Comment by ajh123** [comment]
Also sometimes when deleting a building / road which has people on it can cause some of them be confused.

**Comment by ajh123** [comment]
I've seem to have released most of them by using a proper street instead of drive towards the freight station. Apparently they were trying to go there.

**Comment by Uriopass** [comment]
Oh yeah deletion is definitely not very good today. I have lots of things everywhere that expect stuff to not be deleted.
Indeed, they were trying to go to the freight station to buy bread most probably! You need to build bakeries :D

**Comment by ajh123** [comment]
Which I did have. Probably not enough so I've gone bankrupt now.

**Comment by Uriopass** [comment]
Going bankrupt doesn't have any practical impact as of now, and it's quite hard to make money too. I think a dumb but possible strategy is to build a huge amount of solar panels

**Comment by Uriopass** [comment]
I see the tick in the save and the last tick in the replay are not the same (the replay stopped earlier). Did you just not play in between or did you do some other actions before saving?

**Comment by Uriopass** [comment]
With the hecs removal rework and slotmap rewrite there should be much less serialization issues
