### ISSUE TITLE
Leaner "Inspect" for cars and people

### ISSUE THREAD

**Issue by thelazyone** [Uriopass/Egregoria#80]
The info box when clicking a house contains exactly what a player (not a dev) would expect: the name of the owner and the current residents.
With cars or people, however, there's a heap of information that gameplay-wise might not be necessary. 
A simple tick "show debug" (disabled by default) would be enough to convey only the relevant information to the player.

![image](https://github.com/Uriopass/Egregoria/assets/10134358/df936261-067d-4c4b-a226-ed0f4557b092)

The "Debug Pathfinder" option is very useful, and possibly even desirable for the player: a tick in the "Car" or "Person" box containing that option too would be probably neat.

**Comment by Uriopass** [comment]
Very good first issue for a new contributor !

**Comment by Uriopass** [comment]
![image](https://github.com/Uriopass/Egregoria/assets/5420739/ce0e17a4-c320-422e-8680-c6d20894b411)
![image](https://github.com/Uriopass/Egregoria/assets/5420739/b14612d2-d65c-4a21-9bf8-893822c48fb5)
![image](https://github.com/Uriopass/Egregoria/assets/5420739/681f3e75-b292-4d3c-b75e-525c0552761a)

Added leaner inspects (with optional debug info like the old inspector)

**Comment by Uriopass** [comment]
They're a bit crude atm but more info will be added over time
