### ISSUE TITLE
UX improvement: Automatic "Unfollow" when CMB is dragged

### ISSUE THREAD

**Issue by thelazyone** [Uriopass/Egregoria#81]
Currently the "follow" option for car and people is toggled via a relatively small button in a debug tab full of other information (see #80 ). 

I would suggest that "follow" button to appear in the smaller tab (as part of the #80 issue) but also automatically set as "unfollow" when the player drag the CMB to look around. This would make for a smoother UX, and encourage players to follow more often, for the sake of it.

**Comment by Uriopass** [comment]
Just to clarify, that would indeed be great if unfollow happened when you moved the camera (not necessarily CMB once I finish implementing rebinding). Anyway, should be quite easy to do, good first issue!

**Comment by thelazyone** [comment]
That is correct. I assumed CMB would be the only camera move, but it's just
the default one.

**Comment by Uriopass** [comment]
Fixed in 419fef87d5a765e9806cfc050f1cc0db3d8e9842

**Comment by thelazyone** [comment]
That's great! I'll try to work on the other asap!
