### ISSUE TITLE
Street lights appearing for deleted Roads and overlapping without blending

### ISSUE THREAD

**Issue by thelazyone** [Uriopass/Egregoria#82]
Currently the illumination of the streets does not keep in account the deletion of previous roads. 
![image](https://github.com/Uriopass/Egregoria/assets/10134358/1a4fcb43-b5c7-4c55-b65b-7188df4ae877)
Improvements could be re-generating the baked lights every now and then (at least once per day).
A side-effect of the problem is that the texture of previous now-deleted roads get cut roughly (as in the screenshot).

Attempting a similar cut on non-deleted roads proved that the lights system is otherwise solid.

**Comment by Uriopass** [comment]
Absolutely, the light implementation is still very rough and early, this is a known issue.

I'd really like to develop a smarter way to have road-related textures and models being updated. Having the issue tracked is great however.

**Comment by Uriopass** [comment]
Fixed with the map subscriber rewrite: 825c14244f01f13628c540e095ccba8490ccf969 and 2239779ea5451763284f91b4d7ce0e9c4947b527
