### ISSUE TITLE
200 seconds per hour?

### ISSUE THREAD

**Issue by Kesyau** [Uriopass/Egregoria#86]
The in-game clock behaves weirdly.  It seems that an hour has 66 minutes, and that the clock ticks only three times per minute.

Why is `SECONDS_PER_HOUR` in `egregoria/src/utils/time.rs` 200 rather than 3600?

**Comment by Uriopass** [comment]
Yeah it's a fine balance. Too slow and the night lasts too long and the game progresses too slowly. 
Too fast and the days move too fast and people don't have time to go places.
I have put a constraint that 1s in game = 1s IRL so it's easier. So I'm tuning day length with seconds_per_hour but there's probably something better

**Comment by Uriopass** [comment]
Done in 05b396a1
